language: python
python:
  - "3.6"
notifications:
  slack: ibm-research:bLcRT4dofYlBUocjPBvlxO9p
  email: 
    recipients:
    - tidhamecha@in.ibm.com
    on_success: always
    on_failure: always

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc

script:
  - echo "skipping tests"	
#   - py.test -s # or py.test for Python versions 3.5 and below

deploy:
- provider: cloudfoundry
  username: apikey
  password: $apikey
  api: https://api.ng.bluemix.net
  organization: tidhamecha
  space: here
  manifest: manifest.yml
  on:
    branch: develop